# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_doctor_docuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=20)),
                ('medicine_text', models.CharField(choices=[('paracetomal', 'crocin-advance'), ('paracetomal', 'dolo')], max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('pharmauser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
