# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='image_url',
            field=models.CharField(default='', max_length=20),
        ),
    ]
